### ISSUE TITLE
Turpial 1.3.2 a1 se cuelga después de autenticar la cuenta

### ISSUE THREAD

**Issue by cwsevilla** [satanas/Turpial#11]
Después de autenticar la cuenta, en el momento que actualiza el timeline se cuelga el sistema. El mensaje después de la depuración es el siguiente:

DEBUG:Gtk:Actualizando el timeline
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.6/turpial/api/turpialapi.py", line 663, in run
    callback(rtn)
  File "/usr/lib/pymodules/python2.6/turpial/ui/gtk/main.py", line 463, in update_timeline
    count = self.home.timeline.update_tweets(tweets)
  File "/usr/lib/pymodules/python2.6/turpial/ui/gtk/tweetslist.py", line 430, in update_tweets
    self.add_tweet(tweet)
  File "/usr/lib/pymodules/python2.6/turpial/ui/gtk/tweetslist.py", line 379, in add_tweet
    pango_twt = self.__highlight_hashtags(pango_twt)
  File "/usr/lib/pymodules/python2.6/turpial/ui/gtk/tweetslist.py", line 96, in __highlight_hashtags
    (self.mainwin.link_color, h)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 5: unexpected end of data

**Comment by satanas** [comment]
Deprecated
