### ISSUE TITLE
Does not start Turpial ("turpial -i qt") // Turpial no inicia. ("turpial -i qt")

### ISSUE THREAD

**Issue by talueses** [satanas/Turpial#129]
Regards!

Try init turpial with "turpial -i qt" this happened:

pidfile /tmp/turpial-daemon.pid does not exist. Daemon not running?
Abyssinica SIL
Bitstream Charter
Cantarell
Century Schoolbook L
Courier 10 Pitch
DejaVu Sans
DejaVu Sans Mono
DejaVu Serif
Dingbats
FreeMono
FreeSans
FreeSerif
gargi
Garuda
Gentium
Gentium Basic
Gentium Book Basic
GentiumAlt
KacstArt
KacstBook
KacstDecorative
KacstDigital
KacstFarsi
KacstLetter
KacstNaskh
KacstOffice
KacstOne
KacstPen
KacstPoster
KacstQurn
KacstScreen
KacstTitle
KacstTitleL
Kedage
Khmer OS
Khmer OS System
Kinnari
Liberation Mono
Liberation Sans
Liberation Sans Narrow
Liberation Serif
LKLUG
Lohit Bengali
Lohit Gujarati
Lohit Hindi
Lohit Punjabi
Lohit Tamil
Loma
Mallige
Meera
Monospace
mry_KacstQurn
Mukti Narrow
NanumGothic
NanumMyeongjo
Nimbus Mono L
Nimbus Roman No9 L
Nimbus Sans L
Norasi
OpenSymbol
ori1Uni
Padauk
Padauk Book
Phetsarath OT
Pothana2000
Purisa
Rachana
Rekha
Saab
Sans Serif
Sawasdee
Serif
Standard Symbols L
Symbol
TakaoPGothic
Tibetan Machine Uni
Tlwg Typist
Tlwg Typo
TlwgMono
TlwgTypewriter
Ubuntu
Ubuntu Condensed
Ubuntu Mono
Umpush
URW Bookman L
URW Chancery L
URW Gothic L
URW Palladio L
Vemana2000
Waree
WenQuanYi Micro Hei
WenQuanYi Micro Hei Mono
start
Traceback (most recent call last):
  File "/usr/local/bin/turpial", line 9, in <module>
    load_entry_point('turpial==1.9.7-a1', 'console_scripts', 'turpial')()
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/main.py", line 104, in main
    t = Turpial()
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/main.py", line 79, in **init**
    self.ui.show_main()
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/ui/qt/main.py", line 159, in show_main
    self.update_container()
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/ui/qt/main.py", line 221, in update_container
    self._container.normal()
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/ui/qt/container.py", line 77, in normal
    self.columns[column.id_] = StatusesColumn(self.base, column.id_)
  File "/usr/local/lib/python2.7/dist-packages/turpial-1.9.7_a1-py2.7.egg/turpial/ui/qt/column.py", line 60, in **init**
    self.protocol_id = get_protocol_from(self.account_id)
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/common/**init**.py", line 40, in get_protocol_from
    return account_id.split('-')[1]
IndexError: list index out of range

**Comment by satanas** [comment]
Hi @talueses, try deleting the config folder `~/.config/turpial` and register again your account. I've fixed the error saving so you should be able to do it now without problem.

Regards
