### ISSUE TITLE
Hack this shit

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#222]
Traceback (most recent call last):
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/main.py", line 358, in add_column
    self.core.save_column(column_id)
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/worker.py", line 356, in save_column
    reg_column_id = self.core.register_column(column_id)
  File "/Users/satanas/proyectos/libturpial/libturpial/api/core.py", line 151, in register_column
    return self.column_manager.register(column_id)
  File "/Users/satanas/proyectos/libturpial/libturpial/api/managers/columnmanager.py", line 62, in register
    self.config.write('Columns', key, column_id)
  File "/Users/satanas/proyectos/libturpial/libturpial/config.py", line 145, in write
    self.__config[section][option] = value
KeyError: 'Columns'

**Comment by satanas** [comment]
Apparently hacked ~~fixed~~
