### ISSUE TITLE
Error on connection to twitter

### ISSUE THREAD

**Issue by ogranada** [satanas/Turpial#252]
When add a new account to Turpial I got the next error:

``` python
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/accounts.py", line 162, in __register_twitter_account
    self.base.save_account(account)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/main.py", line 363, in save_account
    self.core.save_account(account)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/worker.py", line 333, in save_account
    self.load_account(account_id, trigger_signal=False)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/worker.py", line 342, in load_account
    self.core.accman.load(account_id)
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/api/managers/accountmanager.py", line 54, in load
    self.__accounts[account_id] = Account.load(account_id)
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/api/models/account.py", line 152, in load
    key, secret, verifier = account.config.load_oauth_credentials()
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/config.py", line 336, in load_oauth_credentials
    raise EmptyOAuthCredentials
EmptyOAuthCredentials

<class 'libturpial.exceptions.EmptyOAuthCredentials'>: 
```

If I try to add the same account anew y got the next error:

``` python
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/accounts.py", line 162, in __register_twitter_account
    self.base.save_account(account)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/main.py", line 363, in save_account
    self.core.save_account(account)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/worker.py", line 332, in save_account
    account_id = self.core.register_account(account)
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/api/core.py", line 119, in register_account
    return self.accman.register(account)
  File "/usr/local/lib/python2.7/dist-packages/libturpial-1.0-py2.7.egg/libturpial/api/managers/accountmanager.py", line 70, in register
    raise AccountAlreadyRegistered
AccountAlreadyRegistered

<class 'libturpial.exceptions.AccountAlreadyRegistered'>:
```

**Comment by satanas** [comment]
AFAIR this error was fixed on development version. Can you try development version and tell me if it continues?
