### ISSUE TITLE
"Give me a minute" message won't disappear

### ISSUE THREAD

**Issue by cmlnet** [satanas/Turpial#267]
I installed version 3.0 from the Ubuntu PPA and after launching it the "Hi there! Give me a minute, I am shaking my feathers and stretching my wings..." message won't disappear. 

Running Turpial in debug mode provides the following:

```
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
DEBUG:AppConfig:Started
DEBUG:AppConfig:CONFIG_FILE: /home/cml/.config/turpial/config
DEBUG:AppConfig:FILTERS_FILE: /home/cml/.config/turpial/filtered
DEBUG:AppConfig:FRIENDS_FILE: /home/cml/.config/turpial/friends
DEBUG:Controller:Starting Turpial 3.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py", line 592, in after_core_initialized
    width, height = self.core.get_window_size()
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/worker.py", line 509, in get_window_size
    config['Window']['size'] = "320,480"
KeyError: 'Window'
```

**Comment by satanas** [comment]
Yes, there is a bug related to this issue and has been fixed in libturpial 1.5.9. I encourage you to upgrade libturpial to make Turpial work again.

Check the official announce for more information http://turpial.org.ve/2014/01/upgrade-libturpial-to-1-5-9/
