### ISSUE TITLE
Core instance has no attribute 'account_manager' 

### ISSUE THREAD

**Issue by githubrsys** [satanas/Turpial#280]
### occours when hitting relogin in Accounts window

Window shows message "Wait! That account does not exist"

<code>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/accounts.py", line 176, in __relogin_account
    self.base.load_account(account_id)
  File "/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/main.py", line 366, in load_account
    self.core.load_account(account_id)
  File "/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/ui/qt/worker.py", line 319, in load_account
    self.register(self.core.account_manager.load, (account_id),
AttributeError: Core instance has no attribute 'account_manager'

<type 'exceptions.AttributeError'>: Core instance has no attribute 'account_manager'
</code>

**Comment by satanas** [comment]
What version were you using when this message poped up?

**Comment by githubrsys** [comment]
Was a GIT, but don´t really remember which because so much time passed since then.

**Comment by satanas** [comment]
Got it. Well, this issue was already fixed. Closing
