### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by milmazz** [satanas/Turpial#304]
That's because local variable `exif_data` is referenced before assignment. I already fixed, wait my PR.

```
Traceback (most recent call last):
  File "/Development/Turpial/turpial/ui/qt/main.py", line 828, in after_get_image_preview
    self.image_view.load_from_object(response)
  File "/Development/Turpial/turpial/ui/qt/imageview.py", line 205, in load_from_object
    self.__load(media.path)
  File "/Development/Turpial/turpial/ui/qt/imageview.py", line 111, in __load
    self.exif_data.setText(exif_data)
UnboundLocalError: local variable 'exif_data' referenced before assignment
```

**Comment by milmazz** [comment]
Fixed on f0a371b00d786f951eb2a355ac46f209d4004572
