### ISSUE TITLE
Be aware of this

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#310]
Traceback (most recent call last):
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/main.py", line 671, in after_update_column
    self._container.update_column(column.id_, updates)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/container.py", line 226, in update_column
    self.columns[column_id].update_statuses(statuses)
KeyError: 'satanas82-twitter-replies'

**Comment by satanas** [comment]
And this Traceback (most recent call last):
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/main.py", line 829, in update_profile_avatar
    self.profile_dialog.update_avatar(str(image_path), str(username))
  File "/Users/satanas/proyectos/turpial2/turpial/ui/qt/profile.py", line 252, in update_avatar
    if username != self.profile.username or not self.showed:

**Comment by satanas** [comment]
Fixed
