### ISSUE TITLE
Preferences dialog not showing up

### ISSUE THREAD

**Issue by schwindp** [satanas/Turpial#318]
turpial-3.0-3.fc19.noarch

When clicking on Preferences the only action I see on the console is:

<pre>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/main.py", line 278, in show_preferences_dialog
    self.preferences_dialog = PreferencesDialog(self)
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/preferences.py", line 44, in __init__
    self.browser_page = BrowserPage(base)
  File "/usr/lib/python2.7/site-packages/turpial/ui/qt/preferences.py", line 256, in __init__
    self.command.setText(current_browser)
TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'NoneType'
</pre>

**Comment by satanas** [comment]
This was fixed on the development version and will be available in the next stable release
