### ISSUE TITLE
Adding new Twitter account displays error despite apparent success

### ISSUE THREAD

**Issue by PartisanEntity** [satanas/Turpial#319]
Current behaviour:
1. Add new account
2. Go through the app authorization process and enter pin number
3. Turpial displays error: "Error creating account"
4. Close Turpial, relaunch Turpial. Account is there and columns can be added

Expected behaviour:

If there is success in adding the account, Turpial should not display an error.

OS: Ubuntu 14.04
Turpial version: 3.0+dfsg-1

**Comment by satanas** [comment]
Thanks for reporting. This issue was solved and the fix will be available in the next version of Turpial.

**Comment by bentolor** [comment]
Same here. Is a new version already available and what is the best way to upgrade for Debian/Ubuntu-based distros?

**Comment by kixiro** [comment]
Same problem.

~$ turpial 
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/accounts.py", line 161, in __register_twitter_account
    account.authorize_oauth_access(pin)
  File "/usr/lib/python2.7/dist-packages/libturpial/api/models/account.py", line 169, in authorize_oauth_access
    self.profile = self.protocol.authorize_token(pin)
  File "/usr/lib/python2.7/dist-packages/libturpial/lib/protocols/twitter/twitter.py", line 96, in authorize_token
    self.http.authorize_token(pin)
  File "/usr/lib/python2.7/dist-packages/libturpial/lib/http.py", line 331, in authorize_token
    self.token = oauth.OAuthToken.from_string(req.text)
  File "/usr/lib/python2.7/dist-packages/oauth/oauth.py", line 142, in from_string
    key = params['oauth_token'][0]
KeyError: 'oauth_token'

<type 'exceptions.KeyError'>: 'oauth_token'

Ubuntu 14.04
Version: 3.0+dfsg-1
