### ISSUE TITLE
Dont show preferences windows

### ISSUE THREAD

**Issue by aasanchez** [satanas/Turpial#354]
after install turpial from github, cant open preferenses windows... this is the message in terminal

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.5.9_dev-py2.7.egg/turpial/ui/qt/main.py", line 315, in show_preferences_dialog
    self.preferences_dialog = PreferencesDialog(self)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.5.9_dev-py2.7.egg/turpial/ui/qt/preferences.py", line 43, in **init**
    self.notifications_page = NotificationsPage(base)
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.5.9_dev-py2.7.egg/turpial/ui/qt/preferences.py", line 180, in **init**
    tooltip=i18n.get('notify_on_updates_tooltip'))
  File "/usr/local/lib/python2.7/dist-packages/turpial-3.5.9_dev-py2.7.egg/turpial/ui/qt/preferences.py", line 479, in **init**
    self.checkbox.setChecked(self.value)
TypeError: QAbstractButton.setChecked(bool): argument 1 has unexpected type 'str'

**Comment by mnurolcay** [comment]
Same here with Linux Mint 17 KDE

**Comment by satanas** [comment]
This issue has been fixed. Please delete the 'update' and 'actions' options on Notifications section in `~/.config/turpial/config` file (or delete the whole file) and restart Turpial. Everything should work fine after that.
