### ISSUE TITLE
pid file causing problems

### ISSUE THREAD

**Issue by AnandVaidya** [satanas/Turpial#357]
OS (k)Ubuntu Linux 14.04  
Turpial v3.0 from repositories
libturpial v1.6.0

The turpial pid file is stored as /tmp/turpial.pid with ownership of the first person to execute the app - this becomes a problem in multi-user systems  (also /tmp/turpial-debug.html)

When I have two X11 sessions on the same computer, only one user (first one) can start and run turpial - the other user(s) will not be able to start the application. This happens even after the first user quits turpial completely since the pid file is not deleted properly.

The pid file turpial-debug.html etc can be stored inside /tmp/$USERNAME/  

See screenshot below:   ("avdev" is my sw development  acct and "anand" is my acct for other work)

avdev@asp5750$ turpial
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.0', 'console_scripts', 'turpial')()
  File "/usr/lib/python2.7/dist-packages/turpial/main.py", line 106, in main
    t = Turpial()
  File "/usr/lib/python2.7/dist-packages/turpial/main.py", line 66, in **init**
    self.ui = util.INTERFACES[options.interface](debug=options.debug)
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py", line 57, in **init**
    Base.**init**(self)
  File "/usr/lib/python2.7/dist-packages/turpial/ui/base.py", line 28, in **init**
    Singleton.**init**(self, 'turpial.pid')
  File "/usr/lib/python2.7/dist-packages/turpial/singleton.py", line 25, in **init**
    self.fd = open(self.filepath, 'w')
IOError: [Errno 13] Permission denied: '/tmp/turpial.pid'

avdev@asp5750$ ps -ef|grep turp

avdev    17105 17095  0 10:39 pts/8    00:00:00 grep turp

avdev@asp5750$ ls -l /tmp/turpial.pid 
-rw-rw-r-- 1 anand anand 0 Aug 22 10:34 /tmp/turpial.pid

**Comment by satanas** [comment]
Thanks for reporting this. I'll keep an eye on it for the next version
