### ISSUE TITLE
Error en instalacion con fedora 21 

### ISSUE THREAD

**Issue by chudacontreras** [satanas/Turpial#377]
Saludos, turpial al ejecutarlo despues de una instalación limpia en fedora 21 me lanza este error:

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Could not initialize QT interface.
No module named jinja2
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.5.9-dev', 'console_scripts', 'turpial')()
  File "/home/chuda/turpial/turpial/main.py", line 106, in main
    t = Turpial()
  File "/home/chuda/turpial/turpial/main.py", line 66, in **init**
    self.ui = util.INTERFACES[options.interface](debug=options.debug)
TypeError: **init**() got an unexpected keyword argument 'debug'

**Comment by Ryuno-Ki** [comment]
Does #386 fix your problem, @chudacontreras?

How did you try to install Turpial? You're lacking a `jinja` module (version is usually not part of the package). Install it [via pip](https://pypi.python.org/pypi/Jinja2) or [rpm](http://rpmfind.net/linux/rpm2html/search.php?query=python-jinja2) (`python-jinja2`? I'm running Sabayon Linux based on Gentoo Linux …)

Btw. would be super, if you could use [Fenced Code Blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for better readability. My Spanish is a bit rusty :-(

**Comment by Richzendy** [comment]
Hi @chudacontreras , I'm the Fedora Packager to Turpial, I have turpial working fine on Fedora 21 but my actual Fedora was an upgrade from Fedora 20, I'll to make a clean installation of Fedora 21 on a Virtual Machine to try reproduce your bug, thank you for the feedback
