### ISSUE TITLE
Turpial no carga updates

### ISSUE THREAD

**Issue by antelmo** [satanas/Turpial#4]
pues como dice el tema turpial no me carga los updates y al cerrarlo se queda trabado aqui tienen el Log.

DEBUG:API:Iniciado
DEBUG:Controller:Iniciando Turpial
DEBUG:API:Iniciando autenticacion basica
DEBUG:Config:Cargando archivo
DEBUG:Config:Leyendo sección Auth
DEBUG:API:Iniciando OAuth
DEBUG:Gtk:Cargando ventana principal
DEBUG:Gtk:Actualizando configuracion
DEBUG:Config:Leyendo sección Notifications
DEBUG:Gtk:Cambiando a modo wide ((1430, 778))
DEBUG:Gtk:--Creado timer de Timeline cada 3 min
DEBUG:Gtk:--Creado timer de Replies cada 3 min
DEBUG:Gtk:--Creado timer de Directs cada 5 min
DEBUG:API:Descargando Timeline
DEBUG:API:Descargando Replies
DEBUG:API:Descargando Directs
DEBUG:API:Descargando Favorites
DEBUG:API:Descargando Lista de Amigos
DEBUG:Gtk:Actualizando el timeline
/usr/lib/pymodules/python2.6/turpial/ui/gtk/main.py:240: GtkWarning: Failed to set text from markup due to error parsing markup: Error en la línea 3, carácter 78: «3<» no es un nombre válido 
  gtk.main()
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/turpial/api/turpialapi.py", line 439, in run
    rtn = json.loads(self.client.access_resource(oauth_request, uri, method))
  File "/usr/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib/python2.6/json/decoder.py", line 217, in JSONArray
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib/python2.6/json/decoder.py", line 183, in JSONObject
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib/python2.6/json/decoder.py", line 155, in JSONString
    return scanstring(match.string, match.end(), encoding, strict)
ValueError: Unterminated string starting at: line 1 column 56796 (char 56796)
DEBUG:API:Error for URL: http://twitter.com/statuses/mentions.json using parameters: ({'count': 120})
details: None
DEBUG:Gtk:Actualizando las replies
DEBUG:Gtk:Actualizando mensajes directos
DEBUG:Gtk:Actualizando favoritos
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.6/turpial/api/turpialapi.py", line 518, in run
    callback(rtn, args['done'], args['args']['cursor'])
  File "/usr/lib/pymodules/python2.6/turpial/api/turpialapi.py", line 204, in __handle_friends
    for p in rtn['users']:
TypeError: list indices must be integers, not str

DEBUG:API:Descargando Timeline
DEBUG:API:Descargando Replies
DEBUG:Gtk:Guardando tamaño de la ventana
DEBUG:Gtk:--Single: 320, 480
DEBUG:Gtk:--Wide: 1430, 778
DEBUG:Gtk:--Position: 0, 25
DEBUG:Config:Guardando todo
DEBUG:Controller:Desconectando

y ahi se queda, ya han pasado varios minutos y no se cierra y no ha cambiado nada en la consola.

**Comment by satanas** [comment]
Saludos amigo, éste bug ha sido corregido en la versión 1.3.2-a1, puedes probarla o esperar que salga el paquete para tu distribución en instalarla.

Gracias por el aporte

**Comment by antelmo** [comment]
Gracias por el aviso!, esperare el paquete para mi distro =), muy buen trabajo el que están haciendo con Turpial Felicidades!.
