### ISSUE TITLE
Unable to run latest version

### ISSUE THREAD

**Issue by hicolour** [satanas/Turpial#404]
```
2 aur/libturpial-git 1.7.0.602.3de626f-1 [installed] (4) (0.08)
    A library that handles multiple microblogging protocols.
4 aur/turpial-git 3.0.r1647.2c44359-1 [installed: 3.0.r1656.cc59bde-1] (5) (0.05)
    A multi-interface Twitter client written in Python

```

```
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Could not initialize QT interface.
No module named QtWebKit
Traceback (most recent call last):
  File "/usr/bin/turpial", line 11, in <module>
    load_entry_point('turpial==3.5.9.dev0', 'console_scripts', 'turpial')()
  File "/usr/lib/python2.7/site-packages/turpial/main.py", line 106, in main
    t = Turpial()
  File "/usr/lib/python2.7/site-packages/turpial/main.py", line 66, in __init__
    self.ui = util.INTERFACES[options.interface](debug=options.debug)
TypeError: __init__() got an unexpected keyword argument 'debug'
```

**Comment by Richzendy** [comment]
Seems you need QtWebKit installed to run turpial

**Comment by X3MBoy** [comment]
Can I suggest you to use the github version?
