### ISSUE TITLE
Fallo en smlkes.py

### ISSUE THREAD

**Issue by soukron** [satanas/Turpial#8]
Hola!
Estaba probandola y he visto un fallo en el módulo de smlkes.py. 

Al generar un shorturl, aparece el siguiente error:
    Exception in thread Thread-1:
    Traceback (most recent call last):
        File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
            self.run()
        File "/usr/local/lib/python2.6/dist-packages/turpial/api/services.py", line 118, in run
            resp = urlshorter.do_service(args['url'])
        File "/usr/local/lib/python2.6/dist-packages/turpial/api/interfaces/shorturl/smlkes.py", line 20, in do_service
            longurl = self._quote_url(longurl)
    UnboundLocalError: local variable 'longurl' referenced before assignment

Saludos,
Soukron

**Comment by soukron** [comment]
Supongo que con cambiar 
    longurl = self._quote_url(longurl)
por 
    longurl = self._quote_url(keyurl)
sera suficiente, no?

**Comment by satanas** [comment]
Saludos Soukron, el bug ha sido corregido con éxito y está disponible en el repositorio. Proximamente estaremos publicando una nueva alpha con las correcciones

Gracias por el aporte
